import { useEffect, useState } from "react";
import { Controller, useForm } from "react-hook-form";
import Button from "../common/Button";
import Modal from "../common/Modal";
import SubjectForm from "../admin/SubjectForm";
import {
  getLatestSubjectId,
  getAllSubjects,
} from "../../services/subjectService";
import TeacherPicker from "../common/TeacherPicker";

// Derive a lightweight course code such as CSC123 from the name
const generateCourseCode = (courseName = "") => {
  const trimmed = courseName.replace(/[^a-zA-Z]/g, "").toUpperCase();
  const prefix = trimmed.slice(0, 3);
  if (!prefix) return "";
  const hash = Array.from(courseName).reduce(
    (acc, char, index) => acc + char.charCodeAt(0) * (index + 1),
    0
  );
  const numericPart = String(hash % 1000).padStart(3, "0");
  return `${prefix}${numericPart}`;
};

const CourseForm = ({
  onSubmit,
  onCancel,
  loading,
  initialData = {},
  step,
}) => {
  const {
    register,
    handleSubmit,
    control,
    setValue,
    watch,
    formState: { errors },
  } = useForm({
    defaultValues: initialData,
  });

  const [selectedSubjects, setSelectedSubjects] = useState([]);
  const [showSubjectModal, setShowSubjectModal] = useState(false);
  const [availableSubjects, setAvailableSubjects] = useState([]);
  const [loadingAvailableSubjects, setLoadingAvailableSubjects] =
    useState(false);
  const [codeManuallyEdited, setCodeManuallyEdited] = useState(
    Boolean(initialData?.code)
  );
  const [autoGeneratedCode, setAutoGeneratedCode] = useState("");
  const courseName = watch("name");

  // Auto-fill the Subject ID with the latest from backend if not provided
  useEffect(() => {
    let cancelled = false;
    const run = async () => {
      if (initialData && initialData.subjectId) return;
      try {
        const latest = await getLatestSubjectId();
        // If backend returns the latest existing SubjectID, show the next available id (latest + 1)
        if (!cancelled && typeof latest === "number" && !Number.isNaN(latest)) {
          const nextId = latest + 1;
          setValue("subjectId", String(nextId), { shouldValidate: true });
        }
      } catch (_) {
        // ignore; user can type manually
      }
    };
    run();
    return () => {
      cancelled = true;
    };
  }, [initialData, setValue]);

  // Initialize selectedSubjects from initialData if present
  useEffect(() => {
    const list = [];
    if (Array.isArray(initialData?.subjects) && initialData.subjects.length) {
      for (const s of initialData.subjects) {
        if (typeof s === "string") {
          list.push({ id: null, name: s, isNew: false });
        } else if (s && typeof s === "object") {
          list.push({
            id: s.id ?? null,
            name: s.name ?? s.subjectName ?? s.SubjectName ?? "",
            isNew: false,
          });
        }
      }
    } else if (initialData?.subject) {
      list.push({
        id: initialData.subjectId ?? null,
        name: initialData.subject,
        isNew: false,
      });
    } else if (initialData?.subjectId && initialData?.subjectName) {
      list.push({
        id: initialData.subjectId,
        name: initialData.subjectName,
        isNew: false,
      });
    }
    setSelectedSubjects(list);
  }, [initialData]);

  const loadAvailableSubjects = async () => {
    setLoadingAvailableSubjects(true);
    try {
      const subs = await getAllSubjects();
      setAvailableSubjects(subs || []);
    } catch (err) {
      console.error("Failed to load subjects for picker", err);
      setAvailableSubjects([]);
    } finally {
      setLoadingAvailableSubjects(false);
    }
  };

  useEffect(() => {
    // pre-load subjects so picker is responsive
    loadAvailableSubjects();
  }, []);

  useEffect(() => {
    if (initialData?.code) {
      setCodeManuallyEdited(true);
    }
  }, [initialData?.code]);

  useEffect(() => {
    if (initialData?.code || codeManuallyEdited) return;
    if (!courseName) {
      if (autoGeneratedCode) {
        setAutoGeneratedCode("");
        setValue("code", "", { shouldDirty: true, shouldValidate: true });
      }
      return;
    }

    const generated = generateCourseCode(courseName);
    if (!generated || generated === autoGeneratedCode) return;

    setAutoGeneratedCode(generated);
    setValue("code", generated, { shouldDirty: true, shouldValidate: true });
  }, [autoGeneratedCode, codeManuallyEdited, courseName, initialData?.code, setValue]);

  const codeField = register("code", { required: "Course code is required" });

  return (
    <form
      onSubmit={handleSubmit((data) =>
        onSubmit({ ...data, subjects: selectedSubjects })
      )}
      className="space-y-6"
    >
      {/* Step indicator removed per request - show the form directly */}
      <div>
        <label
          htmlFor="name"
          className="block text-sm font-medium text-gray-700 dark:text-gray-300"
        >
          Course Name
        </label>
        <input
          id="name"
          name="name"
          type="text"
          {...register("name", { required: "Course name is required" })}
          className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
        />
        {errors.name && (
          <p className="mt-1 text-sm text-red-600">{errors.name.message}</p>
        )}
      </div>

      <div>
        <label
          htmlFor="code"
          className="block text-sm font-medium text-gray-700 dark:text-gray-300"
        >
          Course Code
        </label>
        <input
          id="code"
          name="code"
          type="text"
          {...codeField}
          onChange={(e) => {
            setCodeManuallyEdited(true);
            codeField.onChange(e);
          }}
          className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
        />
        {errors.code && (
          <p className="mt-1 text-sm text-red-600">{errors.code.message}</p>
        )}
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">
          Assigned Teacher
        </label>
        <Controller
          name="teacherId"
          control={control}
          render={({ field }) => (
            <TeacherPicker
              value={field.value}
              onChange={(val) => field.onChange(val ?? "")}
              onBlur={field.onBlur}
              disabled={loading}
            />
          )}
        />
        {errors.teacherId && (
          <p className="mt-1 text-sm text-red-600">
            {errors.teacherId.message}
          </p>
        )}
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">
          Subjects
        </label>
        <div className="mt-2 space-y-2">
          {selectedSubjects && selectedSubjects.length ? (
            <ul className="list-disc list-inside">
              {selectedSubjects.map((s, idx) => (
                <li
                  key={`${s.name}-${idx}`}
                  className="flex items-center justify-between gap-3"
                >
                  <div className="text-sm">{s.name}</div>
                  <div>
                    <button
                      type="button"
                      onClick={() =>
                        setSelectedSubjects((prev) =>
                          prev.filter((_, i) => i !== idx)
                        )
                      }
                      className="text-sm text-red-600 hover:underline"
                    >
                      Remove
                    </button>
                  </div>
                </li>
              ))}
            </ul>
          ) : (
            <div className="text-sm text-gray-500">No subjects selected.</div>
          )}

          <div className="flex gap-2 pt-2">
            <div className="flex-1">
              <select
                onChange={(e) => {
                  const val = e.target.value;
                  if (!val) return;
                  const found = (availableSubjects || []).find(
                    (a) => String(a.id) === String(val)
                  );
                  if (found) {
                    const name =
                      found.name ??
                      found.subjectName ??
                      found.SubjectName ??
                      "";
                    // avoid duplicates by name
                    if (
                      !selectedSubjects.some(
                        (ss) =>
                          String(ss.name).toLowerCase() ===
                          String(name).toLowerCase()
                      )
                    ) {
                      setSelectedSubjects((prev) => [
                        ...prev,
                        { id: found.id ?? null, name, isNew: false },
                      ]);
                    }
                  }
                  // reset select
                  e.target.value = "";
                }}
                className="w-full rounded-md border-gray-300 p-2 bg-white dark:bg-gray-800"
                disabled={loadingAvailableSubjects}
              >
                <option value="">-- Choose existing subject --</option>
                {(availableSubjects || []).map((s) => {
                  const name = s.name ?? s.subjectName ?? s.SubjectName ?? "";
                  return (
                    <option key={String(s.id)} value={String(s.id)}>
                      {name}
                    </option>
                  );
                })}
              </select>
            </div>

            <div className="flex-shrink-0">
              <Button
                type="button"
                variant="secondary"
                onClick={() => setShowSubjectModal(true)}
              >
                + New
              </Button>
            </div>
          </div>
          {showSubjectModal && (
            <Modal
              isOpen={showSubjectModal}
              onClose={() => setShowSubjectModal(false)}
              title="Add new subject"
              size="md"
            >
              <SubjectForm
                onSubmit={(data) => {
                  const name =
                    data.name ?? data.subjectName ?? data.SubjectName ?? "";
                  setSelectedSubjects((prev) => [
                    ...prev,
                    { id: null, name, isNew: true, draft: data },
                  ]);
                  setShowSubjectModal(false);
                }}
                onCancel={() => setShowSubjectModal(false)}
                initial={{ courseName: initialData?.name }}
              />
            </Modal>
          )}
        </div>
      </div>

      <div>
        <label
          htmlFor="academicYear"
          className="block text-sm font-medium text-gray-700 dark:text-gray-300"
        >
          Academic Year
        </label>
        <input
          id="academicYear"
          name="academicYear"
          type="text"
          {...register("academicYear", {
            required: "Academic year is required",
          })}
          className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
        />
        {errors.academicYear && (
          <p className="mt-1 text-sm text-red-600">
            {errors.academicYear.message}
          </p>
        )}
      </div>

      <div>
        <label
          htmlFor="description"
          className="block text-sm font-medium text-gray-700 dark:text-gray-300"
        >
          Description
        </label>
        <textarea
          id="description"
          name="description"
          rows={3}
          {...register("description")}
          className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
        />
      </div>

      <div className="flex justify-end gap-2">
        {onCancel ? (
          <Button
            type="button"
            variant="secondary"
            onClick={onCancel}
            disabled={loading}
          >
            Cancel
          </Button>
        ) : null}
        <Button type="submit" variant="primary" disabled={loading}>
          {loading ? "Saving..." : "Save Course"}
        </Button>
      </div>
    </form>
  );
};

export default CourseForm;
